

CREATE FUNCTION [dbo].[ufnString_agg]
(    
    @TABLE_SCHEMA NVARCHAR(255),
	@TABLE_NAME NVARCHAR(255)
)
returns  NVARCHAR(MAX)
as

begin
	DECLARE @Chars NVARCHAR(MAX)
		SeLECT  @Chars = ISNULL(@Chars + ', ' +   QUOTENAME(COLUMN_NAME), QUOTENAME(COLUMN_NAME) )  FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = @TABLE_NAME
			AND TABLE_SCHEMA = @TABLE_SCHEMA
    return @Chars
end
