ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\СЛУЖБА];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [securityadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [securityadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [securityadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [NT AUTHORITY\СЛУЖБА];


GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [setupadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [setupadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [setupadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [processadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [processadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [processadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [diskadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [diskadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [diskadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [DESKTOP-NU9LQBU\User];


GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [Cub_];


GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [NT AUTHORITY\LOCAL SERVICE];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\СЛУЖБА];

